routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Cms\BlogCmsController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    return view('welcome');
})->name('index');

Route::get('/produk', function () {
    return view('produk');
})->name('produk');

Route::get('/berita', 'App\Http\Controllers\BlogController@index')->name('berita');
Route::get('/berita/{id}', 'App\Http\Controllers\BlogController@show')->name('berita_detail');

Route::get('/sejarah', function () {
    return view('sejarah');
})->name('sejarah');

Route::get('/sertifikasi', function () {
    return view('sertifikasi');
})->name('sertifikasi');

Route::prefix('cms')->name('cms.')->group(function () {
    Route::resource('blog', BlogCmsController::class); 
    
    Route::get('/dashboard', function () {
        // Uses first & second middleware...
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $blog = Blog::orderBy('created_at', 'DESC')->get();
        return view('berita', compact('blog'));
    }
    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $blog = Blog::where('slug', $id)->firstOrFail();
        return view('berita_detail', compact('blog'));
    }
}

app/Http/Controllers/Cms/BlogCmsController.php
<?php

namespace App\Http\Controllers\Cms;

use App\Models\Blog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BlogCmsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $results = Blog::all();
        return view('cms.blog', compact('results'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('cms.blog_create_edit');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $model = new Blog();
        $model->content = $request->content;
        $model->meta_description = $request->meta_description;
        $model->meta_keyword = $request->meta_keywords;
        $model->title = $request->title;
        $model->slug = str_replace(' ', '-', $request->title . '-' . uniqid());
        $model->banner_title = $request->banner_title;
        $model->writter = 'admin';
        $model->tags = json_encode($request->tags);

        if ($request->hasFile('header_image')) {
            $file = $request->file('header_image');

            $filename = uniqid() . '.' . $file->getClientOriginalExtension();
            $path = $file->storeAs('public/images', $filename);
            $model->header_image = $path;
        }

        if ($request->hasFile('banner_image')) {
            $file = $request->file('banner_image');

            $filename = uniqid() . '.' . $file->getClientOriginalExtension();
            $pathbanner = $file->storeAs('public/images', $filename);
            $model->banner_image = $pathbanner;
        }

        $model->save();

        return redirect(route('cms.blog.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Blog $blog)
    {
        return view('cms.blog_create_edit', compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Blog $blog)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Blog $blog)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/base.blade.php
@include('components.empty')

resources/views/berita.blade.php
@extends('components.empty')

@php
use Carbon\Carbon;
@endphp

@section('content')
<div class="page__banner" data-background="assets/img/bg/page.jpg">
  <div class="container">
      <div class="row">
          <div class="col-xl-12">
              <div class="page__banner-title">
                  <h1>Blog Grid</h1>
                  <div class="page__banner-title-menu">
                      <ul>
                          <li><a href="#">Home</a></li>
                          <li><span>_</span>Blog Grid</li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<div class="blog__area section-padding">
  <div class="container">

    <div class="row">
      @foreach ($blog as $blg)
        <div class="col-xl-4 mb-30">
          <div class="blog__area-item">
            <div class="blog__area-item-image">
              <a href="blog-details.html"><img src="{{ Storage::url($blg->banner_image) }}" alt=""></a>
            </div>
            <div class="blog__area-item-content">
              <div class="blog__area-item-content-meta">
                <ul>
                  <li><a href="#"><i class="fal fa-calendar-alt"></i>{{ Carbon::parse($blg->created_at)->format('j F, Y'); }} </a></li>
                </ul>
              </div>
              <h4><a href="blog-details.html">{{ $blg->title }}</a></h4>
              <a href="{{ route('berita_detail', ['id' => $blg->slug]) }}" class="simple-btn text-success">Read More<i class="fa-solid fa-chevrons-right"></i></a>	
            </div>
          </div>
        </div>
      @endforeach
    </div>

    <div class="row">
      <div class="col-xl-12">
        <div class="theme__pagination t-center mt-50">
          <ul>
            <li><a class="active" href="#">01</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/berita_detail.blade.php
@extends('components.empty')

@php
    use Carbon\Carbon;
@endphp

@section('content')
    <div class="page__banner" data-background="{{ Storage::url($blog->banner_image) }}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="page__banner-title">
                        <h1>{{ $blog->banner_title }} </h1>
                        <div class="page__banner-title-menu">
                            <ul>
                                <li><a href="{{ route('index') }}" class="text-success">Home</a></li>
                                <li class="text-success"><span> / </span> {{ $blog->title }} </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Banner End -->
    <!-- Blog Details Start -->
    <div class="blog__details section-padding">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12 lg-mb-30">
                    <div class="blog__details-left">
                        <img src="{{ Storage::url($blog->header_image) }}" alt="">
                        <div class="blog__details-left-meta">
                            <ul>
                                <li><a href="#"><i class="fal fa-user"></i>By - {{ $blog->writter }} </a></li>
                                <li><a href="#"><i class="fal fa-calendar-alt"></i>{{ Carbon::parse($blog->created_at)->format('j F, Y'); }}</a></li>
                            </ul>
                        </div>
                        {!! $blog->content !!}
                        <div class="blog__details-left-related">
                            <div class="row align-items-center">
                                <div class="col-md-7 md-mb-10">
                                    <div class="blog__details-left-related-tag">
                                        <h6>Tags :</h6>
                                        <ul>
                                            @foreach (json_decode($blog->tags) as $item)
                                              <li><a href="#" class="">{{ $item }}</a></li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-5 t-right md-t-left">
                                    <div class="blog__details-left-related-share">
                                        <ul>
                                            <li><a href="#"><i class="fab fa-facebook-f"></i></a>
                                            </li>
                                            <li><a href="#"><i class="fab fa-twitter"></i></a>
                                            </li>
                                            <li><a href="#"><i class="fab fa-behance"></i></a>
                                            </li>
                                            <li><a href="#"><i class="fab fa-youtube"></i></a>
                                            </li>
                                            <li><a href="#"><i class="fab fa-linkedin-in"></i></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cms/base.blade.php
@include('cms.components.empty')

resources/views/cms/blog.blade.php
@extends('cms.base')

@section('content')
    <div class="page-header">
        <h1 class="page-title">Blog</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header justify-content-between">
                    <h3 class="card-title">List Blog</h3>
                    <div class="float-right">
                        <a href="{{ route('cms.blog.create') }}" class="btn btn-primary btn-block float-end my-2"><i class="fa fa-plus-square me-2"></i>New Blogs</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table border text-nowrap text-md-nowrap mb-0">
                            <thead class="table-primary">
                                <tr>
                                    <th>Judul</th>
                                    <th>Banner</th>
                                    <th>Tags</th>
                                    <th>Penulis</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($results as $result)
                                    <tr>
                                        <td>{{ $result->title }}</td>
                                        <td><img src="{{ Storage::url($result->banner_image)  }}" width="180px" height="90px"></td>
                                        <td>{{ $result->tags }}</td>
                                        <td>{{ $result->writter }}</td>
                                        <td>
                                            <a href="{{ route('cms.blog.edit', $result->id) }}" class="btn btn-icon btn-sm btn-warning"><span class="svg-icon svg-icon-1"><i class="bi bi-pencil-square"></i></span></a>
                                            <button type="submit" form="form-delete-2a8c17fc-4b6d-4216-84c2-eab1cfcfb118" class="btn btn-icon btn-sm btn-danger"><span class="svg-icon svg-icon-1"><i class="bi bi-x-lg"></i></span></button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cms/blog_create_edit.blade.php
@extends('cms.base')

@section('content')
    <div class="page-header">
        <h1 class="page-title">Blog</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header justify-content-between">
                    <h3 class="card-title">Create / Edit Blog</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" id="form-post" action="{{ route('cms.blog.store') }}">
                        @csrf
                        <div class="row">
                            <div class="col-lg-6 col-md-12">
                                <div class="form-group">
                                    <label for="exampleInputname">Judul</label>
                                    <input type="text" class="form-control" id="exampleInputname" name="title">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <div class="form-group">
                                    <label for="exampleInputname1">Judul Banner</label>
                                    <input type="text" class="form-control" id="exampleInputname1" name="banner_title">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-md-12">
                                <div class="form-group">
                                    <label for="exampleInputname">Meta Keywords</label>
                                    <input type="text" class="form-control" id="exampleInputname" name="meta_keywords">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <div class="form-group">
                                    <label for="exampleInputname1">Meta Kewords</label>
                                    <input type="text" class="form-control" id="exampleInputname1"
                                        name="meta_description">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-md-12">
                                <div class="form-group">
                                    <label class="form-label mt-0">Banner Image</label>
                                    <input class="form-control" name="banner_image" type="file" accept="image/*">
                                    <br>
                                    <img src="{{ Storage::url($blog->banner_image)  }}" width="180px" height="90px">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <div class="form-group">
                                    <label for="exampleInputname1">Header Image</label>
                                    <input class="form-control" name="header_image" type="file" accept="image/*">
                                    <br>
                                    <img src="{{ Storage::url($blog->header_image)  }}" width="180px" height="90px">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="exampleInputname1">Tags</label>
                                    <select class="form-control" id="tags" multiple name="tags[]">
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Content</label>
                            <textarea name="content" id="summernote"></textarea>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-end">
                    <a href="javascript:void(0)" class="btn btn-danger my-1">Cancel</a>
                    <button class="btn btn-success my-1" type="submit" form="form-post">Save</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("#tags").select2({
            tags: true
        });
    </script>
@endsection

resources/views/cms/components/empty.blade.php
@include('cms.components.header')
@include('cms.components.navbar')
<!--app-content open-->
<div class="main-content app-content mt-0">
    <div class="side-app">
        <!-- CONTAINER -->
        <div class="main-container container-fluid">
            @yield('content')
        </div>
        <!-- CONTAINER CLOSED -->
    </div>
</div>
<!--app-content closed-->
</div>
@include('cms.components.footer')

resources/views/cms/components/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-md-12 col-sm-12 text-center">
                Copyright © <span id="year"></span> <a href="javascript:void(0)">Sash</a>. Designed with <span class="fa fa-heart text-danger"></span> by <a href="javascript:void(0)"> Spruko </a> All rights reserved.
            </div>
        </div>
    </div>
</footer>
<!-- FOOTER CLOSED -->
</div>

<!-- BACK-TO-TOP -->
<a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>

<!-- JQUERY JS -->
<script src="{{ secure_asset('assets/cms/assets/js/jquery.min.js') }}"></script>

<!-- BOOTSTRAP JS -->
<script src="{{ secure_asset('assets/cms/assets/plugins/bootstrap/js/popper.min.js') }}"></script>
<script src="{{ secure_asset('assets/cms/assets/plugins/bootstrap/js/bootstrap.min.js') }}"></script>

<!-- TypeHead js -->
<script src="{{ secure_asset('assets/cms/assets/plugins/bootstrap5-typehead/autocomplete.js') }}"></script>
<script src="{{ secure_asset('assets/cms/assets/js/typehead.js') }}"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="{{ secure_asset('assets/cms/assets/plugins/p-scroll/perfect-scrollbar.js') }}"></script>
<script src="{{ secure_asset('assets/cms/assets/plugins/p-scroll/pscroll.js') }}"></script>
<script src="{{ secure_asset('assets/cms/assets/plugins/p-scroll/pscroll-1.js') }}"></script>

<!-- SIDE-MENU JS -->
<script src="{{ secure_asset('assets/cms/assets/plugins/sidemenu/sidemenu.js') }}"></script>

<!-- SIDEBAR JS -->
<script src="{{ secure_asset('assets/cms/assets/plugins/sidebar/sidebar.js') }}"></script>

<!-- Color Theme js -->
<script src="{{ secure_asset('assets/cms/assets/js/themeColors.js') }}"></script>

<!-- Sticky js -->
<script src="{{ secure_asset('assets/cms/assets/js/sticky.js') }}"></script>

<!-- CUSTOM JS -->
<script src="{{ secure_asset('assets/cms/assets/js/custom.js') }}"></script>

<!-- Custom-switcher -->
<script src="{{ secure_asset('assets/cms/assets/js/custom-swicher.js') }}"></script>

<!-- Switcher js -->
<script src="{{ secure_asset('assets/cms/assets/switcher/js/switcher.js') }}"></script>


<script src="{{ secure_asset('assets/cms/assets/plugins/summernote/summernote1.js') }}"></script>
<script src="{{ secure_asset('assets/cms/assets/js/summernote.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
@yield('script')
</body>

</html>

resources/views/cms/components/header.blade.php
<!doctype html>
<html lang="en" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="{{ secure_asset('assets/cms/assets/images/brand/favicon.ico') }}">

    <!-- TITLE -->
    <title>Air Bambu CMS</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="{{ secure_asset('assets/cms/assets/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- STYLE CSS -->
     <link href="{{ secure_asset('assets/cms/assets/css/style.css') }}" rel="stylesheet">

	<!-- Plugins CSS -->
    <link href="{{ secure_asset('assets/cms/assets/css/plugins.css') }}" rel="stylesheet">

    <!--- FONT-ICONS CSS -->
    <link href="{{ secure_asset('assets/cms/assets/css/icons.css') }}" rel="stylesheet">

    <!-- INTERNAL Switcher css -->
    <link href="{{ secure_asset('assets/cms/assets/switcher/css/switcher.css') }}" rel="stylesheet">
    <link href="{{ secure_asset('assets/cms/assets/switcher/demo.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body class="app sidebar-mini ltr light-mode">
    @include('cms.components.loader')
    <div class="page">

resources/views/cms/components/loader.blade.php
<div id="global-loader">
    <img src="{{ secure_asset('assets/cms/assets/images/loader.svg') }}" class="loader-img" alt="Loader">
</div>

resources/views/cms/components/navbar.blade.php
<div class="page-main">
    <!-- app-Header -->
    <div class="app-header header sticky">
        <div class="container-fluid main-container">
            <div class="d-flex">
                <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-bs-toggle="sidebar"
                    href="javascript:void(0)"></a>
                <!-- sidebar-toggle-->
                <a class="logo-horizontal " href="index.html">
                    <img src="{{ secure_asset('assets/cms/assets/images/brand/logo-white.png') }}"
                        class="header-brand-img desktop-logo" alt="logo">
                    <img src="{{ secure_asset('assets/cms/assets/images/brand/logo-dark.png') }}"
                        class="header-brand-img light-logo1" alt="logo">
                </a>
                <!-- LOGO -->
                <div class="d-flex order-lg-2 ms-auto header-right-icons">
                    <div class="navbar navbar-collapse responsive-navbar p-0">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                            <div class="d-flex order-lg-2">
                                <!-- SIDE-MENU -->
                                <div class="dropdown d-flex profile-1">
                                    <a href="javascript:void(0)" data-bs-toggle="dropdown"
                                        class="nav-link leading-none d-flex">
                                        <img src="{{ secure_asset('assets/cms/assets/images/users/21.jpg') }}"
                                            alt="profile-user" class="avatar  profile-user brround cover-image">
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                        <div class="drop-heading">
                                            <div class="text-center">
                                                <h5 class="text-dark mb-0 fs-14 fw-semibold">Percy Kewshun</h5>
                                                <small class="text-muted">Senior Admin</small>
                                            </div>
                                        </div>
                                        <div class="dropdown-divider m-0"></div>
                                        <a class="dropdown-item" href="profile.html">
                                            <i class="dropdown-icon fe fe-user"></i> Profile
                                        </a>
                                        <a class="dropdown-item" href="login.html">
                                            <i class="dropdown-icon fe fe-alert-circle"></i> Sign out
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    <div class="sticky">
        <div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
        <div class="app-sidebar">
            <div class="side-header">
                <a class="header-brand1" href="index.html">
                    <img src="{{ secure_asset('assets/cms/assets/images/brand/logo-white.png') }}"
                        class="header-brand-img desktop-logo" alt="logo">
                    <img src="{{ secure_asset('assets/cms/assets/images/brand/icon-white.png') }}"
                        class="header-brand-img toggle-logo" alt="logo">
                    <img src="{{ secure_asset('assets/cms/assets/images/brand/icon-dark.png') }}"
                        class="header-brand-img light-logo" alt="logo">
                    <img src="{{ secure_asset('assets/cms/assets/images/brand/logo-dark.png') }}"
                        class="header-brand-img light-logo1" alt="logo">
                </a>
                <!-- LOGO -->
            </div>
            @include('cms.components.sidebar')
        </div>
    </div>

resources/views/cms/components/sidebar.blade.php
<div class="main-sidemenu">
    <div class="slide-left disabled" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24"
            height="24" viewBox="0 0 24 24">
            <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
        </svg></div>
    <ul class="side-menu">
        <li class="sub-category">
            <h3>Main</h3>
        </li>
        <li class="slide">
            <a class="side-menu__item has-link" data-bs-toggle="slide" href="index.html"><i
                    class="side-menu__icon fe fe-home"></i><span class="side-menu__label">Dashboard</span></a>
        </li>
    </ul>
    <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24"
            height="24" viewBox="0 0 24 24">
            <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
        </svg></div>
</div>

resources/views/sertifikasi.blade.php
@extends('components.empty')

@section('content')
    <div class="page__banner" data-background="{{ asset('assets/img/bg/sertifikasi.png') }}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="page__banner-title">
                        <h1 class="text-green">Sertifikasi</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="product__page section-padding">
      <div class="container">
        <div class="row py-4">
          <div class="col">
            <img class="lazyload" data-src="{{ secure_asset('assets/img/sertifikasi/sertifikat-1.png') }}" alt="logo-image">
          </div>
          <div class="col">
            <img class="lazyload" data-src="{{ secure_asset('assets/img/sertifikasi/sertifikat-2.png') }}" alt="logo-image">
          </div>
        </div>
      </div>
    </div>
@endsection